apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${CONFIG_METALLB_RANGE}
    - name: dns
      protocol: layer2
      addresses:
      - ${CONFIG_METALLB_DNS}/32
      avoid-buggy-ips: true
      auto-assign: false
    - name: traefik
      protocol: layer2
      addresses:
      - ${CONFIG_METALLB_INGRESS}/32
      avoid-buggy-ips: true
      auto-assign: false



      