---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  releaseName: ingress-nginx
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      config:
        custom-http-errors: 404,401,403,500,503
        hsts-max-age: "31449600"
      use-forwarded-headers: "true"
      service:
        type: LoadBalancer
        externalIPs:
        - ${CONFIG_METALLB_INGRESS}
      reportIngressStatus:
        enable: True
        externalService: ingress-nginx-controller
        external-status-address: 
        - ${CONFIG_METALLB_INGRESS}
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: ingress-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "ingress/acme-crt-secret"
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi