---
- name: Build a cluster with single control plane
  hosts: k3s_cluster
  vars:
    k3s_become: true
    k3s_use_unsupported_config: true
    k3s_release_version: v1.23.6+k3s1
    k3s_server:
      write-kubeconfig-mode: '0644'
      disable:
        #- traefik
        #- coredns
        - servicelb
        - local-storage
        - metrics-server
    k3s_server_manifests_urls:
      - url: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
        filename: namespace.yaml
      - url: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
        filename: metallb.yaml
  roles:
    - role: xanmanning.k3s