---
- name: Build a cluster with single control plane
  hosts: k3s_cluster
  vars:
    k3s_become: true
    k3s_use_unsupported_config: true
    k3s_release_version: v1.26.1+k3s1 #v1.23.6-rc1+k3s1
    k3s_server:
      disable-network-policy: true
      flannel-backend: "none"
      cluster-cidr: 172.16.0.0/16,2001:cafe:42:0::/56
      service-cidr: 172.17.0.0/16,2001:cafe:42:1::/112
      write-kubeconfig-mode: '0644'
      disable:
        - flannel
        - traefik
        - servicelb
        - local-storage
        - metrics-server
    k3s_server_manifests_urls:
      - url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      #- url: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
      #- url: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
      - url: https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
  roles:
    - role: xanmanning.k3s