apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:k2c5jy29RWqf/IgSvbqO+soLVg==,iv:WJqZFTVmh6l6JTeLfpTFKv9WIuzvccZMzyicn0habGY=,tag:LhnyR8Yy7KEkxYogOq2ckA==,type:str]
    SECRET_EXTERNAL_DOMAIN2: ENC[AES256_GCM,data:q710Sz6ixif9kA==,iv:pTqCQfOywF7BNW0g9o2OWeiS5mEJ+/t7f89HopNJJPY=,tag:o4hJu/O3NVOsCB4PHSjadA==,type:str]
    SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:xBZwi0VP8S9LcgS9Aft1,iv:5mVl2M/byLKvMvtpojLxr5H7QfKCRK+LWgcJVOBgj9s=,tag:Qdv2mnjoDO5qBxUrfxuyfQ==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:EANWUs9VGY5dRUOEC+ERFI4YligYWPVnM2S2pYwFoDmgTNikwHuKvQ==,iv:US8gYJ3JpN1GvGfxwb6N9lZ3ILcw5JejId22rSmlnDM=,tag:7HRljPfyoqUZcDXv9QDKUQ==,type:str]
    SECRET_VAULTWARDEN_SMTP_PASSWORD: ENC[AES256_GCM,data:0P27M2RwfNAIAzr7ll5tnQflC5KwvdIlrQe9UOPjEwmGuS/rwPQnUguKMl92ra3Z,iv:OHe9/99byt7koJthVXflIhj2iXge4f0Td8x9S7GwjhQ=,tag:9CKyn1FJp0736kpKoo1j4w==,type:str]
    SECRET_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:oeIL12yn4V0c/trSbIru386zIgryfKmy9p1+rK9NuYIIAj5egBqHW36Wr2Zzlw==,iv:ZuMQkpM4SV8ACngVWOl0N3BUncDsp7/uca6cph+KssE=,tag:BpPvgBiCHAiJ6XKrT4d+5w==,type:str]
    SECRET_BOOKSTACK_DB_PASS: ENC[AES256_GCM,data:teLNSkZWLshlWNBTLCixlG/Qc9q9sBY1Sv/I3PspQbDT+68SCrMPsg==,iv:Lqdr3l6e1fT948lyo3dLbiTsEoXOvIOGpkx3i0y61KQ=,tag:F3aWEd/nM9BiIiiKkCOe/A==,type:str]
    SECRET_PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:RoUS31c61+AG2iYl0RBTjTlUB2mSPCVlvNzFUofZcuozBeGFTowniw==,iv:Sea56pyc5xxjZM5B6yyyIJr7OVyV+gbWWsWGxs1BA3E=,tag:aagMGDAN7+7v6AJ6ou0LTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzxq4nsykme3ese225vuqhlluelqnrvvlkfpf4vej5rjfe052srq2w8kuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT0hGY3hkUVhTcnQzblhr
            NVFNYVRzVVFGSmVBd09VMmFWZXhrTnIvWWdZCmZLVU9xOWUwRnI5VDRZdEgrWXZp
            a0VlbC9iRDNoYTB1aVYvbW51Tk9Ra00KLS0tIFZPa0ZCZWw4aHhXZW1tTmZuTFYy
            dkdJVmdObklETG1BY3hHL0YrQUZJaHMKXQX5I4114UC59F3ZEbww8CrVhfVd0uuQ
            C+68XrqCGTUjhSceIaIf0ykeLpa4mCm2uPcGhs9AQMKDrhXwipW7lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T18:14:56Z"
    mac: ENC[AES256_GCM,data:VRXAELVIWkxXcdvJ8Xp8lU0FiFyxDD0y8xAYZpBOrM35Gbwg+MnDLfAWUmfj3RylvcGmY8+j8hWS5PFdmHw9g4W4iZcpHlyE7hL/r3PLLKOnVJ+iam/FXO3UJHvCOxuEhs8UbI2nSnrslyDWHuqOoyXvDlza9+Sn1zyMRojW1ZM=,iv:kM4OmG48Opn14sV7kq0a0Mc1hV0wzMqSOpwAK/0XcM4=,tag:Zvs8Yn9rqTDO3ym1bjeXng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
