apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.9.2/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.9.2/deploy/examples/operator.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.9.2/deploy/examples/cluster.yaml
  - https://raw.githubusercontent.com/rook/rook/release-1.9/deploy/examples/csi/rbd/storageclass.yaml
  - https://raw.githubusercontent.com/rook/rook/release-1.9/deploy/examples/csi/rbd/snapshotclass.yaml