---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-csi/external-snapshotter/tree/v4.0.1/deploy/kubernetes/snapshot-controller
images:
  - name: gcr.io/k8s-staging-sig-storage/snapshot-controller
    newTag: v5.0.1
patchesStrategicMerge:
  - |-
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: snapshot-controller
      namespace: kube-system
    spec:
      replicas: 3
      template:
        spec:
          containers:
            - name: snapshot-controller
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app: snapshot-controller