---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.15
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    eula:
      accept: true
      company: tobiass1402
      email: tobiass1402@@users.noreply.github.com
    global:
      persistence:
        storageClass: ceph-block
    auth:
      tokenAuth:
        enabled: true
    ingress:
      create: true
      class: traefik
      host: &host "k10.${SECRET_LOCAL_DOMAIN}"
      urlPath: k10
      hosts:
        - *host
    grafana:
      enabled: false